# Chapter 1 SSML — part B (announcement through the end of the exam build)
# Pacing tightens from here: beats shorten as the examination proceeds.

PART_B = """
At ten thirty-one, the classroom speaker clicked.<break time="600ms"/>
Every head lifted.<break time="500ms"/>
Northline's speaker system usually worked only when nobody wanted it to.<break time="700ms"/>
<prosody rate="92%">"Attention, students. All seventeen-year-old students scheduled for the National Aptitude Ascension Examination should report to Multipurpose Two at eleven hundred hours. Bring your district identification card. Testing begins promptly at eleven fifteen."</prosody><break time="800ms"/>
Darius groaned.<break time="450ms"/>
"You're sixteen," Kade said.<break time="350ms"/>
"I'm groaning in solidarity."<break time="350ms"/>
"That's new."<break time="350ms"/>
"I'm growing."<break time="650ms"/>
The speaker clicked off.<break time="600ms"/>
Ms. Alvarez set down her tablet.<break time="500ms"/>
"Mercer."<break time="450ms"/>
Kade looked at her.<break time="450ms"/>
"You have your ID?"<break time="350ms"/>
"Somewhere."<break time="350ms"/>
"Find somewhere."<break time="500ms"/>
He patted the pocket of his hoodie.<break time="450ms"/>
The card was there.<break time="500ms"/>
"Miracle," she said.<break time="400ms"/>
"You set your expectations correctly."<break time="600ms"/>
A couple students laughed.<break time="450ms"/>
Ms. Alvarez did not.<break time="600ms"/>
That was unusual.<break time="600ms"/>
Kade watched her.<break time="500ms"/>
"You nervous?"<break time="350ms"/>
"For you?"<break time="350ms"/>
"For the national integrity of standardized testing."<break time="450ms"/>
"No."<break time="350ms"/>
"Good."<break time="500ms"/>
"I am, however, concerned you'll decide the instructions are philosophically inconsistent and refuse to answer question twelve."<break time="500ms"/>
"That happened once."<break time="300ms"/>
"Twice."<break time="350ms"/>
"The second one really was inconsistent."<break time="650ms"/>
Her mouth twitched.<break time="500ms"/>
Kade counted that as a win.<break time="700ms"/>
"Just take the test," she said.<break time="450ms"/>
He shrugged.<break time="1000ms"/>
||
The Aptitude Ascension Examination had been around longer than Kade had been alive. Every seventeen-year-old in the country took some version of it. The official explanation was that it measured academic reasoning, spatial cognition, reaction speed, systems intuition, stress adaptation, and a dozen other things useful for university admissions, technical apprenticeships, military programs, and Resonance screening.<break time="700ms"/>
That last category was why people cared.<break time="800ms"/>
Thirty-one years after Resonance entered the world, civilization had reorganized itself around the tiny percentage of human beings who could do things everyone else could only watch.<break time="800ms"/>
They stopped collapsing bridges.<break time="450ms"/>
Redirected aircraft during emergencies.<break time="450ms"/>
Worked orbital construction.<break time="450ms"/>
Stabilized coastal barriers during storms.<break time="450ms"/>
Competed in arenas watched by hundreds of millions.<break time="450ms"/>
Wore Conduits worth more than Northline's entire building.<break time="800ms"/>
And every year, a few teenagers walked into testing centers as ordinary kids and walked out with numbers that changed their lives.<break time="800ms"/>
Kade did not expect to be one of them.<break time="700ms"/>
He had learned to distrust any institution promising to reveal what he was capable of.<break time="600ms"/>
Institutions had been explaining what he was capable of for years.<break time="600ms"/>
Mostly they seemed disappointed.<break time="1000ms"/>
A soft chime sounded from the teacher's station.<break time="550ms"/>
Ms. Alvarez checked the message and looked around Room Four.<break time="600ms"/>
"All right. Ten-minute break before testing. Stay on campus. Nobody set anything on fire."<break time="600ms"/>
Darius raised a hand.<break time="400ms"/>
"Clarification."<break time="300ms"/>
"No."<break time="350ms"/>
"You didn't hear the question."<break time="350ms"/>
"I know you."<break time="700ms"/>
Chairs scraped back.<break time="550ms"/>
Kade stayed seated long enough to close his tablet.<break time="600ms"/>
A girl named Tessa passed his desk and tapped his shoulder.<break time="500ms"/>
"What do you think you'll score?"<break time="400ms"/>
"Between zero and whatever the maximum is."<break time="450ms"/>
"That confident?"<break time="350ms"/>
"I like to leave room for outcomes."<break time="500ms"/>
"My cousin got seven twelve last year."<break time="400ms"/>
"Is that good?"<break time="450ms"/>
She stared at him.<break time="400ms"/>
"You know it is."<break time="500ms"/>
He did.<break time="400ms"/>
Everyone did.<break time="700ms"/>
Scores above seven hundred triggered scholarship calls. Eight hundred brought recruiters. Nine hundred became local news.<break time="700ms"/>
The highest score ever recorded was supposedly nine sixty-eight, though there were arguments online about whether the scoring system had changed since then.<break time="600ms"/>
Northline students did not generally contribute to that debate.<break time="800ms"/>
Tessa leaned closer.<break time="450ms"/>
"My aunt says anything over six fifty and they test you for Conduit compatibility."<break time="500ms"/>
"Your aunt also says the moon landing was filmed in Nevada."<break time="500ms"/>
"That was my other aunt."<break time="400ms"/>
"You have a complicated family."<break time="600ms"/>
She gave him a finger and walked away.<break time="800ms"/>
Darius waited until she was gone.<break time="500ms"/>
"You ever think about it?"<break time="350ms"/>
"What?"<break time="350ms"/>
"Getting picked."<break time="600ms"/>
Kade knew exactly what he meant.<break time="500ms"/>
Everyone did.<break time="600ms"/>
He looked at the scratched plastic edge of his desk.<break time="600ms"/>
"No."<break time="500ms"/>
Darius frowned.<break time="450ms"/>
"That was too fast."<break time="350ms"/>
"I've had seventeen years."<break time="400ms"/>
"Nobody thinks about being Resonant at three."<break time="400ms"/>
"I was advanced."<break time="400ms"/>
"I'm serious."<break time="550ms"/>
Kade looked at him.<break time="450ms"/>
Darius was serious too.<break time="550ms"/>
That happened less often than his school file suggested.<break time="700ms"/>
"Sure," Kade said. "When I was twelve."<break time="400ms"/>
"And?"<break time="350ms"/>
"And then I turned thirteen."<break time="400ms"/>
"That doesn't mean anything."<break time="350ms"/>
"It means I got older."<break time="600ms"/>
Darius rolled his eyes.<break time="450ms"/>
Kade smiled.<break time="600ms"/>
The smile did what he wanted it to do.<break time="500ms"/>
Conversation over.<break time="800ms"/>
That was one of the useful things about jokes. People thought they were openings.<break time="600ms"/>
Mostly they were doors he could close without anybody noticing.<break time="1200ms"/>
||
At ten fifty-six, Ms. Alvarez stopped him at the classroom door.<break time="600ms"/>
The others filed past.<break time="600ms"/>
"Kade."<break time="450ms"/>
He turned.<break time="500ms"/>
She leaned against the teacher's desk with her arms folded.<break time="550ms"/>
"What?"<break time="350ms"/>
"Nothing."<break time="450ms"/>
"That's usually not why people say my name like that."<break time="600ms"/>
She studied him.<break time="600ms"/>
"You know what I think your problem is?"<break time="450ms"/>
"Alphabetical or ranked?"<break time="650ms"/>
"You decide something doesn't matter before you find out whether you're good at it."<break time="800ms"/>
His smile stayed in place.<break time="500ms"/>
"Efficient."<break time="500ms"/>
"No."<break time="700ms"/>
The word landed harder than it should have.<break time="800ms"/>
Ms. Alvarez nodded toward the hallway.<break time="500ms"/>
"Go take the test."<break time="600ms"/>
He turned away.<break time="550ms"/>
"And Kade?"<break time="500ms"/>
He looked back.<break time="600ms"/>
<prosody rate="88%">"Try."</prosody><break time="900ms"/>
He almost made a joke.<break time="600ms"/>
For some reason, he didn't.<break time="1600ms"/>
"""
